/*
 * This file is generated by using
 *  $ bash tensorflow/tools/git/gen_git_source.sh version_info.cc
 * And it is supposed to be used as
 *  tensorflow/core/util/version_info.cc
 */
#include <string>
const char* tf_git_version() {return "v1.10.1/Debian";}
const char* tf_compiler_version() {
#ifdef _MSC_VER
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
	return "MSVC " TOSTRING(_MSC_FULL_VER);
#else
	return __VERSION__;
#endif
}
const int tf_cxx11_abi_flag() {
#ifdef _GLIBCXX_USE_CXX11_ABI
	return _GLIBCXX_USE_CXX11_ABI;
#else
	return 0;
#endif
}
const int tf_monolithic_build() {
#ifdef TENSORFLOW_MONOLITHIC_BUILD
	return 1;
#else
	return 0;
#endif
}
