#!/bin/bash
set -ex

# required variables ([*]=must)
# src [*]
# elf [*]
# flags
# libs
# incs

# CXX
xe -avj0 g++ -O2 -fPIC $flags -c -I/usr/include/tensorflow $incs -- "${src[@]}"
# LD
g++ -fPIE -pie -O2 $flags -Wl,--start-group \
	-ltensorflow_cc -ltensorflow_framework $libs \
	*.o \
	-Wl,--end-group -o $elf

./$elf

rm *.o
if [[ -z $_CC_NORM ]]; then
rm $elf
fi
