#!/bin/bash
set -ex

# required variables ([*]=must)
# src [*]
# elf [*]
# flags
# libs
# incs
# tflib \in {c, cc, f}, default=f

CXX="ccache g++"
XE=xe
_tflib=( -ltensorflow_framework )

if [[ 'c' = $tflib ]]; then
	_tflib+=( -ltensorflow )
elif [[ 'cc' = $tflib ]]; then
	_tflib+=( -ltensorflow_cc )
fi

_add_src_and_retry() {
	$XE -avj0 $CXX -O2 -fPIC $flags -c -I/usr/include/tensorflow $incs -- "${src[@]}" tensorflow/core/platform/test_main.cc
	$CXX -fPIE -pie -O2 $flags -Wl,--start-group \
		${_tflib[@]} $libs \
		*.o \
		-Wl,--end-group \
		-o $elf
}

# CXX
$XE -avj0 $CXX -O2 -fPIC $flags -c -I/usr/include/tensorflow $incs -- "${src[@]}"
# LD
$CXX -fPIE -pie -O2 $flags -Wl,--start-group \
	${_tflib[@]} $libs \
	*.o \
	-Wl,--end-group -o $elf || _add_src_and_retry

./$elf 

rm *.o
if [[ -z $_CC_NORM ]]; then
	rm $elf
fi
