#!/bin/sh
set -x


case $1 in
	clean)
		sh debian/shogun-clean.sh
		;;
	distclean)
		git clean -xdfq
		git checkout .
		;;
	pre)
		sh debian/embedded.sh
		cp debian/patches/version_info.cc tensorflow/core/util/version_info.cc
		sh debian/shogun-gen.sh
		;;
	post)
		quilt pop -a
		rm -rf debian/embedded/eigen3 debian/embedded/fft || true
		;;
	*)
		echo Invalid command
		;;
esac

